[package]
name = "reverse"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokenizer = { path = "../tokenizer" }
parser = { path = "../parser" }
vm = { path = "../vm" }