[package]
name = "portal-wasm-build"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path="../core" }
common = { path="../common" }
wasm = { path="../wasm" }
wasm-bindgen = "0.2.80"
anyhow = "1.0.57"