pub const CANT_CONVERT_VALUE: &str = "Could not convert external value";
pub const FUNCTION_INCORRECT_NUMBER_OF_PARAMETERS: &str = "Incorrect number of parameters passed to a function";
pub const EXTERNAL_FUNCTION_INCORRECT_NUMBER_OF_PARAMETERS: &str = "Incorrect number of parameters passed to an external function";
pub const EXTERNAL_FUNCTION_PARAMETER_WRONG_TYPE: &str = "A parameter passed to an external function has a wrong type"; 
pub const VARIABLE_NOT_DECLARED: &str = "The variable is not declared in this context";
pub const VARIABLE_IS_NOT_A_NUMBER: &str = "Variable is not a number";
pub const VARIABLE_IS_NOT_A_FUNCTION: &str = "Tried invoking a variable that is not a function";
pub const MODULE_NOT_FOUND: &str = "Module not found";
pub const INVALID_IDENTIFIER: &str = "Invalid module identifier";
